language: python

os:
  - linux

python:
  - 3.5
  - 3.6

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

git:
  depth: false

# safelist
branches:
  only:
  - master

install:
  - pip install -r requirements.txt
  - pip install .

script: pytest