language: python

os:
  - linux

python:
  - "3.5"
  - "3.6"
  - "3.7"

git:
  depth: false

# safelist
branches:
  only:
  - master

install:
  - pip install -r requirements.txt
  - pip install .

script: pytest