language: python

os:
  - linux

python:
  - 3.5
  - 3.6

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - os: osx
      python: 3.5
      language: generic
      env: CONDAENV=3.5
    - os: osx
      python: 3.6
      language: generic
      env: CONDAENV=3.6
    - os: osx
      python: 3.7
      language: generic
      env: CONDAENV=3.7

git:
  depth: false

# safelist
branches:
  only:
  - master

before_install:
  - ./.travis/install.sh

install:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source activate testenvironment
  - pip install -r requirements.txt
  - pip install .

script: pytest

