language: python

python:
  - "3.5"
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch

git:
  depth: false

# safelist
branches:
  only:
  - master

install:
  - pip install .

script: pytest