language: python

os:
  - windows
  - linux
  - osx

python:
  - "3.5"
  - "3.6"

git:
  depth: false

# safelist
branches:
  only:
  - master

install:
  - pip install -r requirements.txt
  - pip install .

script: pytest